spring.application.name=api


spring.datasource.url=jdbc:postgresql://localhost:5432/aps
spring.datasource.username=erickms
spring.datasource.password=erickms
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true